### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by mikelpint** [gengjiawen/desktop#12]
I am writing an AUR package to install GitHub Desktop on Arch Linux and its derivatives.
Could I upload it to the AUR?

This is the current PKGBUILD:
[PKGBUILD.zip](https://github.com/gengjiawen/desktop/files/1163553/PKGBUILD.zip)

**Comment by gengjiawen** [comment]
Feel free to upload it to ther aur, I only do the packaging here :)
