### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by rawsh** [gengjiawen/desktop#13]
Can we get one?

**Comment by gengjiawen** [comment]
Just curious, does Red hat use gnome as desktop environment?

**Comment by mikelpint** [comment]
Yes, it does.

**Comment by gengjiawen** [comment]
I will give it a try, hope you guys can test it for me.

**Comment by mikelpint** [comment]
Be sure xD

**Comment by gengjiawen** [comment]
Please give https://github.com/gengjiawen/desktop/releases/tag/v0.7.1-beta4 a try？

**Comment by mikelpint** [comment]
I'm con holydays right now so i can't help you. I will be back con Sunday.

**Comment by mikelpint** [comment]
How do you build the packages from the source code?

**Comment by gengjiawen** [comment]
I am using travis ci.

**Comment by mikelpint** [comment]
Thanks :)

**Comment by rawsh** [comment]
Testing it now @gengjiawen

**Comment by rawsh** [comment]
![screenshot from 2017-07-27 10-31-24](https://user-images.githubusercontent.com/7035671/28678748-c97ada92-72b6-11e7-9e0d-3437cb5cb553.png)

Works great, thanks! One issue is that it does not list my repos from github, I had to add local to get it to work.
