### ISSUE TITLE
Add icon for window

### ISSUE THREAD

**Issue by Epat9** [gengjiawen/desktop#14]
### Description
App have default X11 icon 

### Version

**GitHub Desktop version:** 0.7.1-beta4

**OS version:** Kubuntu 16.04.2

### Steps to Reproduce

1. Just install from .deb or .appimage file
2. Launch it

**Expected behavior:** I expected app to have Github Desktop icon 

**Actual behavior:** Instead it have default x11 app icon or default Plasma5 app icon

**Reproduces how often:** 100%

**Comment by ZeroDot1** [comment]
![bildschirmfoto_2017-09-12_15-55-53](https://user-images.githubusercontent.com/28985171/30329564-e7f656f4-97d2-11e7-908e-55b522d2d1db.png)

**Comment by gengjiawen** [comment]
I notice this problem too, I think I have the right config, will look into it.

**Comment by gengjiawen** [comment]
Reported issue link: https://github.com/electron-userland/electron-builder/issues/2098.

**Comment by gengjiawen** [comment]
Please try https://github.com/shiftkey/desktop/releases, for more, please refer to README.md
