### ISSUE TITLE
Error: cannot open shared object file

### ISSUE THREAD

**Issue by ZeroDot1** [gengjiawen/desktop#15]
### Description

Error: cannot open shared object file

### Version

**GitHub Desktop version:** [v0.8.2-beta1]

**OS version:** 
```bash
System:    Host: A632-OS Kernel: 4.12.13-1-ARCH x86_64 bits: 64
           Desktop: Xfce 4.12.4 Distro: Antergos Linux
Machine:   Device: desktop Mobo: MSI model: 760GM-P23(FX) (MS-7641) v: 3.0 serial: N/A
           BIOS: American Megatrends v: V17.15 date: 04/28/2013
CPU:       Dual core AMD Athlon II X2 270 (-MCP-) cache: 2048 KB
           clock speeds: max: 3400 MHz 1: 2000 MHz 2: 2000 MHz
Graphics:  Card: NVIDIA GT215 [GeForce GT 240]
           Display Server: x11 (X.Org 1.19.3 ) driver: nvidia
           Resolution: 1920x1080@60.05hz
           OpenGL: renderer: GeForce GT 240/PCIe/SSE2
           version: 3.3.0 NVIDIA 340.102
Audio:     Card-1 NVIDIA High Def. Audio Controller driver: snd_hda_intel
           Card-2 Advanced Micro Devices [AMD/ATI] SBx00 Azalia (Intel HDA)
           driver: snd_hda_intel
           Sound: Advanced Linux Sound Architecture v: k4.12.13-1-ARCH
```

### Steps to Reproduce

1. Open Github Desktop
2. Click Fetch origin

#### Additional Information: 
https://aur.archlinux.org/packages/github-desktop/

Screenshot:
![bildschirmfoto_2017-09-21_19-34-31](https://user-images.githubusercontent.com/28985171/30709857-ecf6d290-9f03-11e7-9a77-bd5ba433f597.png)

**Comment by mikelpint** [comment]
Try installing libcurl-compat.

**Comment by mikelpint** [comment]
I did a clean Arch Linux installation a few days ago in my laptop and it worked perfectly.

**Comment by mikelpint** [comment]
I will add that packages to the list of dependencies later anyway.

**Comment by ZeroDot1** [comment]
libcurl-compat is installed.
![bildschirmfoto_2017-09-21_19-46-19](https://user-images.githubusercontent.com/28985171/30710340-8f1f316a-9f05-11e7-9368-a1fd4737c4c1.png)

**Comment by mikelpint** [comment]
And libcurl-gnutls?

**Comment by ZeroDot1** [comment]
That was not installed, is now done.

**Comment by mikelpint** [comment]
Is it working well now?

**Comment by ZeroDot1** [comment]
Now it works again, thanks for the quick support.
