### ISSUE TITLE
Add support for Options/Advandes/Shell selection

### ISSUE THREAD

**Issue by mullnerz** [gengjiawen/desktop#16]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by gengjiawen** [comment]
I have no plan to support feature for this. I want to limit this repo to keep linux build only.
