### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by JCSzamosi** [gengjiawen/desktop#18]
### Description

Although I appear to be successfully signed in to my github account, and I can pull and see private repositories, when I push to a repo that I do not own (but do have edit privileges on) I get an authentication failure. I can push to that same remote from the command line with the same credentials.

### Version

**GitHub Desktop version:** it says 0.7.1-beta4, but I don't know because it's a linux fork

**OS version:** Ubuntu 16.0.4

**Comment by anhbinhvodanh** [comment]
Try using the lastest version https://github.com/gengjiawen/desktop/releases

**Comment by gengjiawen** [comment]
Can you provide the debug info in `View -> Toggle develop tools` ?

**Comment by Croydon** [comment]
@gengjiawen It's broken for me because it can't find libcurl-gnutls.so.4

> renderer.js:29 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
/tmp/.mount_mQUT2D/usr/bin/resources/app/node_modules/dugite/git/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

> install.ts:23` git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
/tmp/.mount_mQUT2D/usr/bin/resources/app/node_modules/dugite/git/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory

**Comment by ederancz** [comment]
@gengjiawen  similar issue here with latest release (1.0.4-beta0) - I can see my repos put can't clone an oranisational one - exactly same thing works on macOS GitHub Desktop 1.0.13. (repo exists and I have access)
Here is the error message: 

install.ts:23 `git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/SainsburyWellcomeCentre/LSFM_Stitcher.git /home/rancze/Documents/GitHub/LSFM_Stitcher` exited with an unexpected code: 2.
Cloning into '/home/rancze/Documents/GitHub/LSFM_Stitcher'...
remote: Repository not found.
fatal: repository 'https://github.com/SainsburyWellcomeCentre/LSFM_Stitcher.git/' not found
Error(s) during clone:
git clone failed: exit status 128

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

**Comment by gengjiawen** [comment]
Please try https://github.com/shiftkey/desktop/releases, for more, please refer to README.md
