### ISSUE TITLE
pushing and pulling error

### ISSUE THREAD

**Issue by solinium** [gengjiawen/desktop#2]
by default, if you try to push or pull with the AppImage or .deb on Ubuntu 17.04, it will fail with message: fatal: Unable to find remote helper for 'https'

it seems that re-compiling it with libcurl4-openssl-dev might fix it

**Comment by gengjiawen** [comment]
Can you use 0.5.8 and share the stacktrace by opening develop tools in Menu `View -> Toggle develop tools`.
And I don't see desktop depends on  libcurl4-openssl-dev lib.

**Comment by solinium** [comment]
here is the log: https://pastebin.com/yUN7Yxt7

this seems to be the issue:
install.ts:19 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: Unable to find remote helper for 'https'

**Comment by gengjiawen** [comment]
Seems like bundling problem. I will take a look.

**Comment by gengjiawen** [comment]
I believe 0.6.1 fix this, please give a try https://github.com/gengjiawen/desktop/releases.
