### ISSUE TITLE
Can't login to GitHub

### ISSUE THREAD

**Issue by tabepic** [gengjiawen/desktop#20]
### Description

When I try to clone a repo from GitHub (for example), it asks me to login to GitHub. After authenticating, the following message shows up (when started from terminal) and I'm still not logged in.
`** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

### Version

**GitHub Desktop version:** 1.0.4-beta0

**OS version:** Arch Linux (up-to-date)

**Comment by gengjiawen** [comment]
Can you try this version: https://github.com/gengjiawen/desktop/releases/tag/v0.8.2-beta1.

**Comment by mikelpint** [comment]
Try installing gnome-keyring.

**Comment by tabepic** [comment]
@mikelpint Thanks, it works fine now. This should be a dependency for the AUR package.
I'll suggest it to the maintainer.

**Comment by mikelpint** [comment]
@tabepic I am the maintainer so I will add it now.
