### ISSUE TITLE
Patch the icon in Gnome 3

### ISSUE THREAD

**Issue by MayukhSobo** [gengjiawen/desktop#21]
The icon looks weird in Gnome 3 fedora and the default icon is not visible. Moreover whenever the application is opened, it doesn't use that same icon in the launch bar but rather opens a separate icon. 

![dock](https://user-images.githubusercontent.com/8527634/32543818-b124c1aa-c49c-11e7-8795-589ebde25c1a.png)

The 9th icon from the beginning is the desktop icon. 
![opened](https://user-images.githubusercontent.com/8527634/32543911-fda892a4-c49c-11e7-9586-4c2b648e2027.png)

The last icon is when it is opened..Please fix this

**Comment by MayukhSobo** [comment]
https://github.com/gengjiawen/desktop/issues/14

**Comment by mikelpint** [comment]
This happens because the desktop file used by the app is desktop and not github

**Comment by mikelpint** [comment]
Modify the /usr/share/applications/desktop.desktop file.
