### ISSUE TITLE
Linux version larger than necessary?

### ISSUE THREAD

**Issue by probonopd** [gengjiawen/desktop#3]
Why is the AppImage for Linux so much larger than e.g., the Windows download?

Inside the AppImage, there is a 1.3 GB file `app.asar` __plus__ 110 MB folder `app.asar.unoacked`. Is this all really needed?

**Comment by solinium** [comment]
It's compiled by travis so it's not manually compiled or anything, I don't think you could change it.

**Comment by probonopd** [comment]
Well, something must be wrong if the Windows exe can be so small...

**Comment by gengjiawen** [comment]
I notice this too, and this result in i can't build more linux distro in travis. Since travis build time is limit to 1 hour. I report this to electron-builder, but I think mostly this related to this project itself. Anyway I will take a look into this.

**Comment by gengjiawen** [comment]
Well, I can't unpack the asar due to this https://github.com/electron/asar/issues/116.

**Comment by gengjiawen** [comment]
I know why linux distro is so big, because https://github.com/desktop/dugite-native is very large on linux. There is nothing i can do about it.

**Comment by probonopd** [comment]
What does it do? Maybe it would be more efficient to bundle a normal `git` inside the AppImage.

**Comment by gengjiawen** [comment]
I have reported this issue https://github.com/desktop/dugite-native/issues/47. I looked into the folder, it's actually bundle of git binary, like git, git-lfs, git-add.

**Comment by probonopd** [comment]
Sorry, I still don't get it. dugite-native-v2.13.0-ubuntu-188.tar.gz is only 39 MB. Something is about 1 GB (Gigabyte) too large. I don't think it's dugite-native.

**Comment by gengjiawen** [comment]
Unpack it you will find it quite large. Let's do the following talk it in the dugite-native and everyone related can see it.
