### ISSUE TITLE
Add support for "Login in browser"

### ISSUE THREAD

**Issue by theel0ja** [gengjiawen/desktop#5]
The redirect back isn't working (using Chrome)

**Comment by gengjiawen** [comment]
Can you retry with 0.6.1, and show debug info if still not working in menu `View -> Toggle develop tools`.

**Comment by theel0ja** [comment]
It works, but redirection back to app not working (Chrome can't find the protocol binding (or whatever it is))

**Comment by gengjiawen** [comment]
Give the 0.7.0 a try, I am not family with the code, maybe it's a bug in original repo.

**Comment by wraithmgn** [comment]
# @

**Comment by kuro68k** [comment]
It's not working for me on 0.7.1 and Chrome either.

**Comment by kleinen** [comment]
I just tested 0.7.1-beta4 on Ubuntu 14.04 against a Github Enteprrise server and saw the same.  It opened Chrome fine, but never returned back.

**Comment by gengjiawen** [comment]
I am not a Github Enterprise user, so test this case for me is a little hard. Did you see any log in console ?

**Comment by gengjiawen** [comment]
Please try https://github.com/shiftkey/desktop/releases, for more, please refer to README.md
