### ISSUE TITLE
Linux Error Cloning

### ISSUE THREAD

**Issue by qwertysam** [gengjiawen/desktop#6]
### Description

When I try to clone a repository I get a popup error with the text `spawn ENOTDIR`

### Version

**GitHub Desktop version:** v0.5.9

Operating system: Ubuntu 16.04 (64 bit)

### Steps to Reproduce

1. Open GitHub Desktop
2. Attempt cloning repository
3. Get error `spawn ENOTDIR`

This is the repository I'm attempting to clone
https://github.com/qwertysam/shooty-game
It is a new repository with no modifications made to the permissions. All that's been done is 3 commits have been made.

**Expected behaviour:** The repository to clone.

**Actual behaviour:** It didn't clone.

**Reproduces how often:** Every time I try to clone

### Logs

These are the only two messages that appear in the console when creating this error.

```
Uncaught (in promise) Error: ENOENT, emoji.json not found in /opt/GithubDesktop/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFile (ELECTRON_ASAR.js:468:16)
    at Promise (/home/samson/webpack:/app/src/lib/dispatcher/emoji-store.ts:93:18)
    at I.EmojiStore.read (/home/samson/webpack:/app/src/lib/dispatcher/emoji-store.ts:90:11)
    at Me.loadEmoji (/home/samson/webpack:/app/src/lib/dispatcher/app-store.ts:200:25)
    at requestIdleCallback (/home/samson/webpack:/app/src/ui/app.tsx:107:15)
Executing clone: git -c credential.helper= clone --recursive --progress --progress -- https://github.com/qwertysam/shooty-game.git /home/samson/Documents/GitHub/shooty-game
```

#### Additional Information

I tried some basic debugging, using different forms for the URL of the Git repository, creating the required directories manually, running `sudo desktop` and none of that helped.

**Comment by gengjiawen** [comment]
I notice the problem too, I have not find why. But i will take a look when i have time.

**Comment by gengjiawen** [comment]
Looks like compatibility problem dugite with electron-builder. I will look what i can do.

**Comment by gengjiawen** [comment]
I believe 0.6.1 fix this, please give a try https://github.com/gengjiawen/desktop/releases.

**Comment by qwertysam** [comment]
Yup, works like a charm, great work! But oops, [I'm causing more trouble](https://github.com/gengjiawen/desktop/issues/7)
