### ISSUE TITLE
Linux error when pushing commits

### ISSUE THREAD

**Issue by qwertysam** [gengjiawen/desktop#7]
### Description

When attempting to push a commit, the following error appears in a popup box

```
error: cannot run /opt/GithubDesktop/resources/app/dist/static/ask-pass-trampoline.sh: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

This is the error that appears in the console just before the error occurs

```
Executing push: git -c credential.helper= push origin master:master --progress
renderer.js:18 `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
error: cannot run /opt/GithubDesktop/resources/app/dist/static/ask-pass-trampoline.sh: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### Version

**GitHub Desktop version:** v0.6.1

**OS version:** Ubuntu 16.04 (64 bit)

### Steps to Reproduce

1. Clone a repository
2. Edit some files
3. Commit
4. Attempt to push commits

The repository I'm attempting to push to
https://github.com/qwertysam/shooty-game

**Comment by gengjiawen** [comment]
I can reproduce it, I will find a time to take a look, thanks for feedback.

**Comment by gengjiawen** [comment]
Can you try https://github.com/gengjiawen/desktop/releases/tag/v0.6.2-beta1 ?

**Comment by gengjiawen** [comment]
Please try https://github.com/gengjiawen/desktop/releases/tag/v0.6.2-beta2.

**Comment by GrahamCampbell** [comment]
I am finding that cloning repos isn't working for private repos. Similar problem?

**Comment by solinium** [comment]
I get this:
`fatal: cannot exec '/opt/GithubDesktop/resources/app/dist/static/ask-pass-trampoline.sh': Permission denied
fatal: could not read Username for 'https://github.com': terminal prompts disabled`
when pushing.
I'm on Debian 9 Stretch using 0.6.2-beta2.
It looks like the same error.

**Comment by qwertysam** [comment]
Still experiencing the same error

**Comment by gengjiawen** [comment]
Please give https://github.com/gengjiawen/desktop/releases/tag/v0.6.2-beta3 a try.

**Comment by qwertysam** [comment]
Pushing and pulling works now, thank you!
