### ISSUE TITLE
Unable to open console for repo

### ISSUE THREAD

**Issue by GrahamCampbell** [gengjiawen/desktop#8]
![image](https://user-images.githubusercontent.com/2829600/27448266-13e9594c-577c-11e7-9d88-18f23b00d38e.png)

Running Ubuntu 17.04, 0.6.2-beta2.

**Comment by gengjiawen** [comment]
Confirmed. But I may not have time to fix this recently.

**Comment by gengjiawen** [comment]
Please try https://github.com/gengjiawen/desktop/releases/tag/v0.6.3-beta1.

**Comment by GrahamCampbell** [comment]
Works. :+1:
