### ISSUE TITLE
Unable to clone private repos

### ISSUE THREAD

**Issue by GrahamCampbell** [gengjiawen/desktop#9]
Ubuntu 17.04, desktop_0.6.3-beta1_amd64.deb. Just get not found back, like the repo doesn't exist.

**Comment by solinium** [comment]
Works fine for me,  desktop_0.6.3-beta1_amd64.deb, Debian Stretch 9.0

**Comment by GrahamCampbell** [comment]
I think the issue is that it's using the wrong ssh key to clone the repos.

**Comment by gengjiawen** [comment]
Can you provide more information by opening develop tools in Menu `View -> Toggle develop tools` ?

**Comment by gengjiawen** [comment]
Closing due inactivity.
